#!/usr/bin/env Rscript

##
## Clustering analysis – Plot a + Plot b (from pre-exported CSVs)
##
## Inputs (generated by `python_scripts/prepare_plot_a_b_data.py`):
## - chapters/03-manuscript-figures/figure_3/data/plot_a.csv
## - chapters/03-manuscript-figures/figure_3/data/plot_b.csv
##
## Output:
## - chapters/03-manuscript-figures/figure_3/R_scripts/clustering_plot_a_b_grid.png
##


suppressPackageStartupMessages({
    library(ggplot2)
    library(dplyr)
    library(readr)
    library(tidyr)
})

text_colour <- "#434343"
grid_colour <- "#ececec"

# --- Styling copied from `figure_2/Figure_2.R` / `R_scripts/variant_pleiotropy_plot.R` ---
base_theme <- theme_minimal() +
    theme(
        text = element_text(face = "plain", color = text_colour),
        axis.title = element_text(size = 8, face = "plain", color = text_colour),
        axis.text = element_text(size = 8, face = "plain", color = text_colour),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = grid_colour, linewidth = 0.3),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(face = "plain", color = text_colour, size = 8),
        legend.key = element_rect(fill = "white", colour = NA),
        legend.background = element_rect(fill = "white", colour = NA),
        plot.tag = element_text(face = "bold", size = 10, colour = text_colour)
    )

tag_theme <- function(x = 0) {
    theme(plot.tag.position = c(x, 1))
}

pal_model_type <- c(
    Univariate = "#245780",
    Joint = "#528B78"
)

# NOTE: user-updated palette (keep as-is)
pal_series <- c(
    "Observed (traits in cluster)" = "#3583C0",
    "Predicted (full model)" = "#A01813",
    "Predicted (no power)" = "#D65A1F"
)

get_script_path <- function() {
    # When called via source("..."), R sets `sys.frame(1)$ofile`
    ofile <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
    if (!is.null(ofile) && nzchar(ofile)) {
        return(ofile)
    }

    # When called via Rscript, the script path is available as `--file=...`
    args <- commandArgs(trailingOnly = FALSE)
    file_arg <- grep("^--file=", args, value = TRUE)
    if (length(file_arg) == 1) {
        return(sub("^--file=", "", file_arg))
    }

    ""
}

script_path <- get_script_path()
figure_3_dir <- if (nzchar(script_path)) dirname(dirname(script_path)) else ""

plot_a_path <- file.path(figure_3_dir, "data", "plot_a.csv")
plot_b_path <- file.path(figure_3_dir, "data", "plot_b.csv")

# Fallback for interactive use
if (!file.exists(plot_a_path)) plot_a_path <- "data/plot_a.csv"
if (!file.exists(plot_b_path)) plot_b_path <- "data/plot_b.csv"

if (!file.exists(plot_a_path)) stop("Could not find plot_a.csv at: ", plot_a_path)
if (!file.exists(plot_b_path)) stop("Could not find plot_b.csv at: ", plot_b_path)

message("Reading Plot a data from: ", plot_a_path)
message("Reading Plot b data from: ", plot_b_path)

df_a <- readr::read_csv(plot_a_path, show_col_types = FALSE)
df_b <- readr::read_csv(plot_b_path, show_col_types = FALSE)

is_plot_a_schema <- function(df) {
    required <- c("model_type", "coefficient", "ci_lower", "ci_upper", "y_numerical")
    all(required %in% names(df))
}

is_plot_b_schema <- function(df) {
    required <- c("maxMAF_bin")
    has_required <- all(required %in% names(df))
    # typical columns for plot b after python export
    has_some_series <- any(grepl("^(observed|predicted_.*)_(mean|sem)$", names(df)))
    has_required && has_some_series
}

# If the user renamed/swapped the input files, detect by schema and swap internally.
if (is_plot_b_schema(df_a) && is_plot_a_schema(df_b)) {
    message("Detected that plot_a_path contains Plot b schema and plot_b_path contains Plot a schema. Swapping inputs internally.")
    tmp <- df_a
    df_a <- df_b
    df_b <- tmp
} else if (!is_plot_a_schema(df_a)) {
    stop(
        "Plot a input does not match expected schema. Missing columns: ",
        paste(setdiff(c("model_type", "coefficient", "ci_lower", "ci_upper", "y_numerical"), names(df_a)), collapse = ", "),
        "\nInput file: ", plot_a_path
    )
} else if (!is_plot_b_schema(df_b)) {
    stop(
        "Plot b input does not match expected schema. Expected `maxMAF_bin` and *_mean/*_sem columns.\n",
        "Input file: ", plot_b_path
    )
}

# -----------------------------
# Plot a (forest-style)
# -----------------------------
df_a_plot <- df_a %>%
    mutate(
        # Be explicit about dplyr::recode() to avoid masking by other packages (e.g. car::recode)
        model_type = dplyr::recode(as.character(model_type), Multi = "Joint", .default = as.character(model_type)),
        model_type = factor(model_type, levels = c("Univariate", "Joint"))
    )

y_breaks <- df_a_plot %>%
    distinct(y_numerical, covariate_label) %>%
    arrange(y_numerical)

p_a <- ggplot(df_a_plot, aes(
    x = coefficient,
    y = y_plot,
    colour = model_type
)) +
    geom_vline(xintercept = 0, colour = "#bdbdbd", linetype = "dashed", linewidth = 0.4) +
    # ggplot2 >= 4.0 deprecated geom_errorbarh(); use geom_errorbar() + orientation instead
    geom_errorbar(
        aes(xmin = ci_lower, xmax = ci_upper),
        orientation = "y",
        width = 0,
        linewidth = 0.4,
        alpha = 0.9
    ) +
    geom_point(size = 1.8, alpha = 0.95) +
    scale_colour_manual(values = pal_model_type) +
    scale_y_continuous(
        breaks = y_breaks$y_numerical,
        labels = y_breaks$covariate_label
    ) +
    labs(
        tag = "b",
        x = "Coefficient (95% CI)",
        y = NULL
    ) +
    base_theme +
    tag_theme(x = -0.03) + # Nudge tag left a bit for the right-hand panel
    theme(
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = grid_colour, linewidth = 0.3)
    )

# -----------------------------
# Plot b (binned observed vs predicted, 95% CI)
# -----------------------------
maf_levels <- c("0-0.01", "0.01-0.05", "0.05-0.1", "0.1-0.2", "0.2-0.3", "0.3-0.4", "0.4-0.5")

df_b_long <- df_b %>%
    mutate(maxMAF_bin = factor(as.character(maxMAF_bin), levels = maf_levels)) %>%
    pivot_longer(
        cols = -maxMAF_bin,
        names_to = c("series", "stat"),
        names_pattern = "^(.*)_(mean|sem)$",
        values_to = "value"
    ) %>%
    pivot_wider(names_from = stat, values_from = value) %>%
    mutate(
        ci = sem * 1.96,
        series = dplyr::recode(series,
            observed = "Observed (traits in cluster)",
            predicted_full = "Predicted (full model)",
            predicted_no_power = "Predicted (no power)"
        ),
        series = factor(series, levels = c(
            "Observed (traits in cluster)",
            "Predicted (full model)",
            "Predicted (no power)"
        ))
    )

p_b <- ggplot(df_b_long, aes(
    x = maxMAF_bin,
    y = mean,
    colour = series,
    fill = series,
    group = series
)) +
    # CI as semi-transparent area (Figure_2 style)
    geom_ribbon(aes(ymin = mean - ci, ymax = mean + ci), alpha = 0.12, linewidth = 0, na.rm = TRUE) +
    geom_line(linewidth = 0.6) +
    scale_colour_manual(values = pal_series) +
    # Let fill+colour merge into a single legend so the key shows the translucent CI band behind the line (Figure 2 style)
    scale_fill_manual(values = pal_series) +
    # Remove default padding so panel (and horizontal gridlines) ends at first/last x bin
    scale_x_discrete(expand = c(0, 0)) +
    labs(
        tag = "a",
        x = "MAF bin",
        y = "Number of traits"
    ) +
    base_theme +
    tag_theme(x = 0) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        # Nudge legend away from the left border of the panel
        legend.box.margin = margin(l = 12)
    )

# -----------------------------
# Combine horizontally and save
# -----------------------------
out_path <- file.path(figure_3_dir, "R_scripts", "clustering_plot_a_b_grid.png")
if (!nzchar(script_path)) {
    # interactive fallback
    out_path <- "R_scripts/clustering_plot_a_b_grid.png"
}

combined <- NULL
if (requireNamespace("patchwork", quietly = TRUE)) {
    suppressPackageStartupMessages(library(patchwork))
    combined <- p_b + p_a + plot_layout(ncol = 2, widths = c(1, 1))
} else if (requireNamespace("cowplot", quietly = TRUE)) {
    suppressPackageStartupMessages(library(cowplot))
    combined <- cowplot::plot_grid(p_b, p_a, ncol = 2, rel_widths = c(1, 1))
} else {
    stop("Please install either 'patchwork' or 'cowplot' to combine the two plots into a grid.")
}

# Save at A4 portrait width (inches). Keep previous aspect ratio (12x4) to avoid distortion.
a4_portrait_width_in <- 8.27
aspect_ratio <- 4 / 12
ggsave(out_path, combined, width = a4_portrait_width_in, height = a4_portrait_width_in * aspect_ratio, units = "in", dpi = 300, bg = "white")
message("Saved: ", out_path)
